___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<img src=https://i.ibb.co/wJW61Y2/Used-cars.jpg width="700" height="200">

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">The Capstone Project of Data Analytics Module</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:150%; text-align:center; border-radius:10px 10px;">Car Price Prediction EDA</p>

# WELCOME!

## Introduction
Welcome to "***AutoScout Data Analysis Project***". This is the capstone project of ***Data Analysis*** Module. **Auto Scout** data which using for this project, scraped from the on-line car trading company in 2019, contains many features of 9 different car models. In this project, you will have the opportunity to apply many commonly used algorithms for Data Cleaning and Exploratory Data Analysis by using many Python libraries such as Numpy, Pandas, Matplotlib, Seaborn, Scipy you will analyze clean dataset.

The project consists of 3 parts:
* First part is related with 'data cleaning'. It deals with Incorrect Headers, Incorrect Format, Anomalies, Dropping useless columns.
* Second part is related with 'filling data'. It deals with Missing Values. Categorical to numeric transformation is done.
* Third part is related with 'handling outliers of data' via Visualisation libraries. Some insights are extracted.

In [27]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

import warnings 
warnings.filterwarnings("ignore") 
warnings.warn("this will not show")

%matplotlib inline

plt.rcParams["figure.figsize"] = (10,6)

sns.set_style("whitegrid") 
pd.set_option('display.float_format', lambda x: '%.3f' % x)

pd.options.display.max_rows = 150 
pd.options.display.max_columns = 100
import json
import regex as re
from datetime import date
from datetime import datetime
from datetime import timedelta

# PART- 1 `( Data Cleaning )`

In [28]:
df0 = pd.read_excel("scout_car_cleaned.xlsx")
df = df0.copy()

In [29]:
df.head()

,Unnamed: 0,make_model,body_type,price,vat,registration,hp,type,previous_owners,make,model,first_registration,body_color,paint_type,upholstery,body,nr_of_doors,nr_of_seats,gearing_type,displacement,cylinders,weight,drive_chain,fuel,co_2_emission,emission_class,gears,country_version,air_cond,bluetooth
0,0,Audi A1,Sedans,15770,VAT deductible,01/2016,66.000,Diesel,2.000,Audi,A1,2016.000,Black,Metallic,"Cloth, Black",Sedans,5.000,5.000,Automatic,1422.000,3.000,1220.000,front,Diesel,99.000,Euro 6,NaN,NaN,Air conditioning,Bluetooth
1,1,Audi A1,Sedans,14500,Price negotiable,03/2017,141.000,Benzin,NaN,Audi,A1,2017.000,Red,NaN,"Cloth, Grey",Sedans,3.000,4.000,Automatic,1798.000,4.000,1255.000,front,Benzin,129.000,Euro 6,7.000,NaN,Air conditioning,Bluetooth
2,2,Audi A1,Sedans,14640,VAT deductible,02/2016,85.000,Diesel,1.000,Audi,A1,2016.000,Black,Metallic,"Cloth, Black",Sedans,4.000,4.000,Automatic,1598.000,NaN,NaN,front,Diesel,99.000,Euro 6,NaN,NaN,Air conditioning,MP3
3,3,Audi A1,Sedans,14500,NaN,08/2016,66.000,Diesel,1.000,Audi,A1,2016.000,Brown,Metallic,NaN,Sedans,3.000,4.000,Automatic,1422.000,3.000,1195.000,NaN,Diesel,99.000,Euro 6,6.000,NaN,Air suspension,Bluetooth
4,4,Audi A1,Sedans,16790,NaN,05/2016,66.000,Diesel,1.000,Audi,A1,2016.000,Black,Metallic,"Cloth, Black",Sedans,5.000,5.000,Automatic,1422.000,3.000,NaN,front,Diesel,109.000,Euro 6,NaN,Germany,Air conditioning,Bluetooth

In [30]:
df.drop("Unnamed: 0", axis=1, inplace=True)

In [31]:
df.size

461651

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 29 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   make_model          15919 non-null  object
 1   body_type           15859 non-null  object
 2   price               15919 non-null  int64
 3   vat                 11406 non-null  object
 4   registration        14322 non-null  object
 5   hp                  15831 non-null  float64
 6   type                15917 non-null  object
 7   previous_owners     9279 non-null   float64
 8   make                15919 non-null  object
 9   model               15919 non-null  object
 10  first_registration  14322 non-null  float64
 11  body_color          15322 non-null  object
 12  paint_type          10147 non-null  object
 13  upholstery          12199 non-null  object
 14  body                15859 non-null  object
 15  nr_of_doors         15707 non-null  float64
 16  nr_of_seats         14942 non-null  float64
 17  gearing_type        15919 non-null  object
 18  displacement        15423 non-null  float64
 19  cylinders           10239 non-null  float64
 20  weight              8945 non-null   float64
 21  drive_chain         9061 non-null   object
 22  fuel                15919 non-null  object
 23  co_2_emission       13483 non-null  float64
 24  emission_class      12291 non-null  object
 25  gears               11207 non-null  float64
 26  country_version     7586 non-null   object
 27  air_cond            14999 non-null  object
 28  bluetooth           14545 non-null  object
dtypes: float64(10), int64(1), object(18)
memory usage: 3.5+ MB

In [33]:
df["registration"] = pd.to_datetime(df["registration"])

In [34]:
df.registration

0       2016-01-01
1       2017-03-01
2       2016-02-01
3       2016-08-01
4       2016-05-01
           ...
15914          NaT
15915   2019-01-01
15916   2019-03-01
15917   2019-06-01
15918   2019-01-01
Name: registration, Length: 15919, dtype: datetime64[ns]

In [35]:
df.isnull().sum()/len(df)*100

make_model            0.000
body_type             0.377
price                 0.000
vat                  28.350
registration         10.032
hp                    0.553
type                  0.013
previous_owners      41.711
make                  0.000
model                 0.000
first_registration   10.032
body_color            3.750
paint_type           36.259
upholstery           23.368
body                  0.377
nr_of_doors           1.332
nr_of_seats           6.137
gearing_type          0.000
displacement          3.116
cylinders            35.681
weight               43.809
drive_chain          43.081
fuel                  0.000
co_2_emission        15.302
emission_class       22.790
gears                29.600
country_version      52.346
air_cond              5.779
bluetooth             8.631
dtype: float64

In [36]:
df.loc[df.isnull().any(axis=1)]

,make_model,body_type,price,vat,registration,hp,type,previous_owners,make,model,first_registration,body_color,paint_type,upholstery,body,nr_of_doors,nr_of_seats,gearing_type,displacement,cylinders,weight,drive_chain,fuel,co_2_emission,emission_class,gears,country_version,air_cond,bluetooth
0,Audi A1,Sedans,15770,VAT deductible,2016-01-01,66.000,Diesel,2.000,Audi,A1,2016.000,Black,Metallic,"Cloth, Black",Sedans,5.000,5.000,Automatic,1422.000,3.000,1220.000,front,Diesel,99.000,Euro 6,NaN,NaN,Air conditioning,Bluetooth
1,Audi A1,Sedans,14500,Price negotiable,2017-03-01,141.000,Benzin,NaN,Audi,A1,2017.000,Red,NaN,"Cloth, Grey",Sedans,3.000,4.000,Automatic,1798.000,4.000,1255.000,front,Benzin,129.000,Euro 6,7.000,NaN,Air conditioning,Bluetooth
2,Audi A1,Sedans,14640,VAT deductible,2016-02-01,85.000,Diesel,1.000,Audi,A1,2016.000,Black,Metallic,"Cloth, Black",Sedans,4.000,4.000,Automatic,1598.000,NaN,NaN,front,Diesel,99.000,Euro 6,NaN,NaN,Air conditioning,MP3
3,Audi A1,Sedans,14500,NaN,2016-08-01,66.000,Diesel,1.000,Audi,A1,2016.000,Brown,Metallic,NaN,Sedans,3.000,4.000,Automatic,1422.000,3.000,1195.000,NaN,Diesel,99.000,Euro 6,6.000,NaN,Air suspension,Bluetooth
4,Audi A1,Sedans,16790,NaN,2016-05-01,66.000,Diesel,1.000,Audi,A1,2016.000,Black,Metallic,"Cloth, Black",Sedans,5.000,5.000,Automatic,1422.000,3.000,NaN,front,Diesel,109.000,Euro 6,NaN,Germany,Air conditioning,Bluetooth
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15914,Renault Espace,Van,39950,VAT deductible,NaT,147.000,Diesel,NaN,Renault,Espace,NaN,Grey,Metallic,NaN,Van,5.000,5.000,Automatic,1997.000,4.000,1758.000,front,Diesel,139.000,NaN,6.000,NaN,Air conditioning,Bluetooth
15915,Renault Espace,Van,39885,VAT deductible,2019-01-01,165.000,Benzin,1.000,Renault,Espace,2019.000,Grey,Metallic,Cloth,Van,5.000,5.000,Automatic,1798.000,4.000,1708.000,front,Benzin,168.000,NaN,7.000,Germany,Air conditioning,Bluetooth
15916,Renault Espace,Van,39875,VAT deductible,2019-03-01,146.000,Diesel,1.000,Renault,Espace,2019.000,White,NaN,"Full leather, Black",Van,5.000,7.000,Automatic,1997.000,4.000,NaN,front,Diesel,139.000,Euro 6d-TEMP,6.000,Austria,Air conditioning,Bluetooth
15917,Renault Espace,Van,39700,VAT deductible,2019-06-01,147.000,Diesel,NaN,Renault,Espace,2019.000,Grey,NaN,Part leather,Van,5.000,7.000,Automatic,1997.000,4.000,1758.000,front,Diesel,139.000,Euro 6,6.000,NaN,Air conditioning,Bluetooth
15918,Renault Espace,Van,40999,VAT deductible,2019-01-01,165.000,Benzin,1.000,Renault,Espace,2019.000,Grey,Metallic,"Full leather, Brown",Van,5.000,5.000,Automatic,1798.000,4.000,1685.000,4WD,Benzin,153.000,Euro 6,NaN,Germany,Air conditioning,USB

In [20]:
x = df.air_cond.mode()[0]
x

'Air conditioning'

In [40]:
# # function to return limit percent of missing values
def show_nans(df, limit):
    missing = df.isnull().sum()*100/df.shape[0]
    return missing.loc[lambda x : x >= limit]
show_nans(df,90)

Series([], dtype: float64)

In [39]:
df.isnull().sum()/len(df)*100

make_model            0.000
body_type             0.377
price                 0.000
vat                  28.350
registration         10.032
hp                    0.553
type                  0.013
previous_owners      41.711
make                  0.000
model                 0.000
first_registration   10.032
body_color            3.750
paint_type           36.259
upholstery           23.368
body                  0.377
nr_of_doors           1.332
nr_of_seats           6.137
gearing_type          0.000
displacement          3.116
cylinders            35.681
weight               43.809
drive_chain          43.081
fuel                  0.000
co_2_emission        15.302
emission_class       22.790
gears                29.600
country_version      52.346
air_cond              5.779
bluetooth             8.631
dtype: float64

# PART- 2 `( Handling With Missing Vales )`

## body_type NaN filling

## vat type NaN filling

## registration type NaN filling

## hp type NaN filling

## type NaN filling

## previous_owners NaN filling

# PART- 3 `( Handling With Outliers )`

# Final Step (Checking final situation of data via graphs)

## Export dataframe to csv file (without dummy)

In [ ]:
df.to_csv("final_scout_not_dummy.csv", index=False)

# Dummy Operation

## Export dataframe to csv file (dummy)

In [ ]:
df_dummied.to_csv("final_scout_dummy.csv", index=False)